services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton_hôte_db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nom_de_ta_db
      - key: DB_USERNAME
        value: utilisateur_db
      - key: DB_PASSWORD
        value: motdepasse
